spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
      - id: productModule
        uri: lb://MS-PRODUCT
        predicates:
        - Path=/products/**

      - id: supplierModule
        uri: lb://MS-SUPPLIER
        predicates:
        - Path=/suppliers/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080